# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kerbals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='kerbal',
        ),
        migrations.AddField(
            model_name='kerbal',
            name='flights',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kerbal',
            name='land',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kerbal',
            name='orbit',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Career',
        ),
    ]
